### ISSUE TITLE
Sveltekit 2

### ISSUE THREAD

**Issue by emb-memi** [railwayapp-templates/svelte-kit#3]
### Hello

Sveltekit 2 was released in the end of last year.
I want to hear if it is in the pipeline to upgrade this repository to use sveltekit 2?

**Comment by Noahtyr** [comment]
Seconded, this template is very efficient and nice to use when building railway apps. Currently, we have to manually migrate. I would be beneficial to have this template build on sveltekit 2, which is also the new standard svelte uses.

**Comment by brody192** [comment]
Updated to Sveltekit v5, closing this out.
